name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initialise Packer
        run: packer init .          

      # validate templates
      - name: Validate Template
        run: packer validate -syntax-only packer.pkr.hcl          

      # build artifact
      - name: Build Artifact
        run: packer build -color=false -on-error=abort -var-file="testing.pkrvars.hcl" .                
        env:
          PACKER_LOG: 1

      - name: List images
        run: docker images

          
